name: 'Slack Integration for GitHub'
description: 'This Action sends pull request and issue event messages to your Slack channel.'
author: 'Hiroyuki Kusu'
branding:
  icon: 'hash'
  color: 'white'
inputs:
  slack-token:
    description: ''
    required: true
  channel:
    description: ''
    required: true
  subscribe-pulls:
    description: ''
    default: 'false'
    required: false
  subscribe-issues:
    description: ''
    default: 'false'
    required: false
  subscribe-reviews:
    description: ''
    default: 'false'
    required: false
  subscribe-pull-comments:
    description: ''
    default: 'false'
    required: false
  subscribe-issue-comments:
    description: ''
    default: 'false'
    required: false
  pull-open-message:
    description: ''
    default: 'Pull request opened by <actor> :sparkles:'
    required: false
  pull-reopen-message:
    description: ''
    default: 'Pull request reopened by <actor> :recycle:'
    required: false
  pull-draft-open-message:
    description: ''
    default: 'Draft pull request opened by <actor> :memo:'
    required: false
  pull-draft-reopen-message:
    description: ''
    default: 'Draft pull request reopened by <actor> :memo:'
    required: false
  pull-ready-message:
    description: ''
    default: 'Pull request ready for review by <actor> :sparkles:'
    required: false
  pull-close-message:
    description: ''
    default: 'Pull request closed by <actor> :heavy_multiplication_x:'
    required: false
  pull-merge-message:
    description: ''
    default: 'Pull request merged by <actor> :twisted_rightwards_arrows:'
    required: false
  pull-comment-message:
    description: ''
    default: ''
    required: false
  issue-open-message:
    description: ''
    default: 'Issue opened by <actor> :sparkles:'
    required: false
  issue-reopen-message:
    description: ''
    default: 'Issue reopened by <actor> :recycle:'
    required: false
  issue-close-message:
    description: ''
    default: 'Issue closed by <actor> :heavy_multiplication_x:'
    required: false
  issue-comment-message:
    description: ''
    default: ''
    required: false
  review-approve-message:
    description: ''
    default: '<actor> approved <author>''s pull request :white_check_mark:'
    required: false
  review-request-changes-message:
    description: ''
    default: '<actor> requested changes on <author>''s pull request :no_entry:'
    required: false
  review-comment-message:
    description: ''
    default: '<actor> commented on <author>''s pull request :speech_balloon:'
    required: false
  app-name:
    description: ''
    required: false
  app-icon:
    description: ''
    required: false
  app-emoji:
    description: ''
    required: false
  footer:
    description: ''
    default: <${{ github.event.repository.html_url }}|${{ github.event.repository.full_name }}>
    required: false
  footer-icon:
    description: ''
    default: ${{ github.event.repository.owner.avatar_url }}
    required: false
  show-pull-actor:
    description: ''
    default: 'true'
    required: false
  show-issue-actor:
    description: ''
    default: 'true'
    required: false
  show-review-actor:
    description: ''
    default: 'true'
    required: false
  show-pull-comment-actor:
    description: ''
    default: 'true'
    required: false
  show-issue-comment-actor:
    description: ''
    default: 'true'
    required: false
  threading-comments:
    description: ''
    default: 'false'
    required: false
  show-pull-detail:
    description: ''
    default: 'true'
    required: false
  show-issue-detail:
    description: ''
    default: 'true'
    required: false
  event-name:
    description: ''
    default: ${{ github.event_name }}
    required: false
  event:
    description: ''
    default: ${{ toJson(github.event) }}
    required: false
  github-token:
    description: ''
    default: ${{ github.token }}
    required: false
outputs:
  result:
    description: '`success` or `failure` is set.'
runs:
  using: 'node16'
  main: 'dist/index.js'
